spring:
  application:
    name: spring-backend
  data:
    redis:
      host: 192.168.206.128
      port: 6379
      password: 123456
      database: 0
  datasource:
    url: jdbc:postgresql://192.168.206.128:5432/java
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect